<head>
  <!-- prevents compatibility view -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- specifies the character encoding for the document --> 
      <meta charset="utf-8" />
  <!-- specifies the base URL/target for all relative URLs -->        
      <base href="https://www.grifare.net/examples/jokes/missile-alert/" />
<title>Armagan TEKDONER - Studio Gri Fare | Missile Alert Joke</title>
<meta name="robots" content="noindex, nofollow" />
<link rel="icon" type="image/x-icon" href="https://www.grifare.info/favicon.ico" />
<link rel="icon" href="https://www.grifare.info/logos/fare-only-180x180.png" sizes="32x32" />
<link rel="icon" href="https://www.grifare.info/logos/fare-only-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="https://www.grifare.info/logos/fare-only-180x180.png" />
<meta name="msapplication-TileImage" content="https://www.grifare.info/logos/fare-only-270x270.png" />
    <!--[if lte IE 9]>
    <link rel="shortcut icon" href="https://www.grifare.info/favicon.ico"> 
    <![endif]-->
  <!-- browser renders the width of the page at the width of its own screen -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
  <!-- app-specific stylesheet never cached -->
      <link rel="stylesheet" href="system/missile-alert.css" type="text/css" />
  <!-- jQuery CDN -->    
      <script src="https://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript" integrity="sha256-8WqyJLuWKRBVhxXIL1jBDD7SDxU936oZkCnxQbWwJVw=" crossorigin="anonymous"></script>
  <!-- app-specific js never cached -->    
	  <script type="text/javascript" src="system/missile-alert.js"></script>
